apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: decision-center
spec:
  href: https://cpd-cp4ba.itzroks-662001rtxj-6ad8ml-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-east.containers.appdomain.cloud/odm/decisioncenter
  location: ApplicationMenu
  applicationMenu:
    section: Operational Decision Manager
  text: Decision Center
